name: Continuous Integration

on: [push, pull_request]

concurrency:
    group: ${{github.head_ref || github.ref}}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]

                node-version: [16.x]
                pnpm-version: [6.32]

        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install Package Dependencies
              run: npm ci

            - name: Install Playwright Dependencies
              run: npx playwright install

            - name: Lint Package
              run: npm run lint:package

            - name: Sync SvelteKit Typings
              run: npm run sync:svelte

            - name: Test Package
              run: npm run test

            - name: Build Package
              run: npm run build:package
